name: test-app-runner

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: npm run build --if-present

      - run: npm install pm2 -g

      - run: pm2 delete all> /dev/null || true
      - run: pm2 start npm --name "test-app" -- run start

    # - run: pm2 reload next-js
    #   env:
    #     CI: true

    # steps:
    #   - uses: actions/checkout@v2

    #   - uses: actions/setup-node@v1
    #     with:
    #       node-version: 18

    #   - name: Install PM2
    #     run: npm install pm2 -g

    #   - name: Instalando paquetes del repo
    #     run: npm install

    #   - name: Building...
    #     run: npm run build

    #   - name: Iniciando...
    #     # run: pm2 delete all
    #     run: pm2 start npm --name "test-app" -- run start
